---
title: "ROC_AUC"
author: "Animesh Kansal"
date: "2/4/2019"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r}
library(pROC)
library(randomForest)
set.seed(420)
```


```{r}
num_samples = 100
weight = sort(rnorm(n = num_samples,mean = 172,sd = 29))
obese = ifelse(test = (runif(n=num_samples) < (rank(weight)/100)), yes = 1,no = 0 )

obese
```


```{r}
plot(x= weight,y = obese)

```

# Logistic regression
```{r}
glm_fit = glm(obese ~ weight, family = binomial)
plot(x= weight,y = obese)
lines(weight,glm_fit$fitted.values)
```

# AUC ROC
```{r}
par(pty = "s")
roc(
obese,
glm_fit$fitted.values,
plot = TRUE,
legacy.axes = TRUE,
percent = TRUE,
xlab = "False Positive Percentage",
ylab = "True Positive Percentage",
col = "#377eb8",
lwd = 4,
print.auc = TRUE
)
```

# Partial AUC ROC
```{r}
par(pty = "s")
roc(
obese,
glm_fit$fitted.values,
plot = TRUE,
legacy.axes = TRUE,
percent = TRUE,
xlab = "False Positive Percentage",
ylab = "True Positive Percentage",
col = "#377eb8",
lwd = 4,
print.auc = TRUE,
print.auc.x = 45,
partial.auc=c(100,90),
auc.polygon = TRUE,
auc.polygon.col = '#377eb822'
)
```

```{r}
roc_info = roc(obese, glm_fit$fitted.values, legacy.axes = TRUE)
roc_def = data.frame(
  tpp = roc_info$sensitivities * 100,
  fpp = (1 - roc_info$specificities) * 100,
  thresholds = roc_info$thresholds
)
print('head')
head(roc_def)
print('tail')
tail(roc_def)
```

# Choose best threshold
```{r}
roc_def[roc_def$tpp>60 & roc_def$tpp < 80 ,]

```

# Random forest classifier
```{r}
rf_model = randomForest(factor(obese) ~ weight)
```


```{r}
par(pty = "s")
roc(
obese,
glm_fit$fitted.values,
plot = TRUE,
legacy.axes = TRUE,
percent = TRUE,
xlab = "False Positive Percentage",
ylab = "True Positive Percentage",
col = "#377eb8",
lwd = 4,
print.auc = TRUE
)

plot.roc(obese,rf_model$votes[,1],percent= TRUE,col = '#4daf4a',lwd = 4,print.auc=TRUE,add=TRUE, print.auc.y=40)

legend("bottomright",legend=c("Random forest","Logistic Regression"),col =c("#4dac4a","#377eb8"),lwd= 4)
```

